version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: gitinsight_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      FLASK_APP: run.py
      FLASK_ENV: production
      DATABASE_URL: postgres://user:password@db:5432/gitinsight_db
    ports:
      - "5001:5000"
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:

