"""Add description and readme fields to Repository

Revision ID: 8fdd183ee5a7
Revises: ff294fc496de
Create Date: 2025-04-25 23:04:54.346042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fdd183ee5a7'
down_revision = 'ff294fc496de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('readme', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_column('readme')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
